/**
 * `TextDecoder` UTF-16LE polyfill for Hermes (React Native's JS engine).
 *
 * ## Why this exists
 *
 * `h3-js` (our hexagon library) ships glue code generated by Emscripten. That
 * glue runs `new TextDecoder('utf-16le')` while it is being imported. On a
 * device, React Native runs on **Hermes**, whose built-in `TextDecoder` only
 * understands `utf-8`. So the constructor throws
 * `RangeError: Unknown encoding: utf-16le`, the exception is uncaught during
 * startup module loading, and the whole app aborts (SIGABRT) about a second
 * after launch — before any UI renders.
 *
 * (The Jest test suite dodged this because `jest.setup.ts` swaps in Node's
 * fully-featured `TextDecoder`. That patch never ships inside the app, so the
 * defect only surfaced on real hardware.)
 *
 * ## The fix
 *
 * If the platform's `TextDecoder` cannot handle `utf-16le`, install a thin
 * wrapper that decodes the UTF-16LE / UCS-2 family ourselves and delegates
 * every other encoding (notably `utf-8`) to the platform implementation, so the
 * fast native path is preserved. If the platform already supports `utf-16le`
 * (iOS' JSC, or a future Hermes), we leave the global untouched.
 *
 * This must run before any module that imports `h3-js`. It is wired up as the
 * very first import in the app entry point (`index.ts`).
 */

type DecoderInput = ArrayBuffer | ArrayBufferView;

interface TextDecodeOptions {
  stream?: boolean;
}

interface TextDecoderOptions {
  fatal?: boolean;
  ignoreBOM?: boolean;
}

/**
 * Minimal structural shape of the platform `TextDecoder`. We avoid depending on
 * the DOM lib types (React Native does not target the DOM) and describe only
 * the surface we actually use.
 */
interface MinimalTextDecoder {
  readonly encoding: string;
  decode(input?: DecoderInput, options?: TextDecodeOptions): string;
}

interface MinimalTextDecoderCtor {
  new (label?: string, options?: TextDecoderOptions): MinimalTextDecoder;
}

// Encoding labels the WHATWG spec maps to the UTF-16LE decoder. Emscripten only
// ever asks for `utf-16le`, but we cover the family so the wrapper is correct.
const UTF16LE_LABELS = new Set([
  'utf-16le',
  'utf-16',
  'ucs-2',
  'unicode',
  'csunicode',
  'iso-10646-ucs-2',
]);

const globalRef = globalThis as unknown as { TextDecoder?: MinimalTextDecoderCtor };
const PlatformTextDecoder = globalRef.TextDecoder;

function normalizeLabel(label: string): string {
  return label.trim().toLowerCase();
}

function toBytes(input?: DecoderInput): Uint8Array {
  if (input === undefined) return new Uint8Array(0);
  if (input instanceof Uint8Array) return input;
  if (ArrayBuffer.isView(input)) {
    return new Uint8Array(input.buffer, input.byteOffset, input.byteLength);
  }
  return new Uint8Array(input);
}

/**
 * Decode little-endian UTF-16 bytes into a string. JavaScript strings are
 * themselves UTF-16, so each 16-bit code unit maps straight through — including
 * surrogate pairs, which need no special handling here.
 */
function decodeUtf16le(bytes: Uint8Array): string {
  const usableLength = bytes.length - (bytes.length % 2);
  const codeUnits: number[] = [];
  for (let i = 0; i < usableLength; i += 2) {
    const low = bytes[i] ?? 0;
    const high = bytes[i + 1] ?? 0;
    codeUnits.push(low | (high << 8));
  }

  // Build the string in chunks so a large buffer cannot overflow the argument
  // limit of `String.fromCharCode(...)`.
  const CHUNK = 8192;
  let result = '';
  for (let i = 0; i < codeUnits.length; i += CHUNK) {
    result += String.fromCharCode(...codeUnits.slice(i, i + CHUNK));
  }

  // A trailing odd byte is malformed UTF-16; emit the Unicode replacement
  // character, matching what a spec-compliant decoder does.
  if (bytes.length % 2 !== 0) result += '�';

  return result;
}

/**
 * `TextDecoder` replacement that understands the UTF-16LE family itself and
 * delegates all other encodings to the platform decoder.
 */
export class Utf16CapableTextDecoder implements MinimalTextDecoder {
  readonly encoding: string;
  readonly fatal: boolean;
  readonly ignoreBOM: boolean;
  private readonly delegate?: MinimalTextDecoder;

  constructor(label: string = 'utf-8', options: TextDecoderOptions = {}) {
    this.fatal = options.fatal ?? false;
    this.ignoreBOM = options.ignoreBOM ?? false;

    if (UTF16LE_LABELS.has(normalizeLabel(label))) {
      this.encoding = 'utf-16le';
      return;
    }

    if (PlatformTextDecoder === undefined) {
      // Should never happen: we only install the polyfill when a platform
      // decoder exists (see installTextDecoderPolyfill). Fail loudly rather
      // than silently returning wrong data.
      throw new RangeError(`Unsupported encoding without a platform TextDecoder: ${label}`);
    }

    this.delegate = new PlatformTextDecoder(label, options);
    this.encoding = this.delegate.encoding;
  }

  decode(input?: DecoderInput, options?: TextDecodeOptions): string {
    if (this.delegate !== undefined) return this.delegate.decode(input, options);
    return decodeUtf16le(toBytes(input));
  }
}

/** True if the platform `TextDecoder` can already decode `utf-16le` correctly. */
function platformSupportsUtf16le(): boolean {
  if (PlatformTextDecoder === undefined) return false;
  try {
    const decoded = new PlatformTextDecoder('utf-16le').decode(new Uint8Array([0x41, 0x00]));
    return decoded === 'A';
  } catch {
    return false;
  }
}

/**
 * Install the UTF-16LE-capable `TextDecoder` globally, but only when needed:
 * - if there is no platform `TextDecoder` at all, there is nothing Emscripten
 *   will try to use, so we leave things alone;
 * - if the platform decoder already handles `utf-16le`, we keep the native one.
 *
 * Idempotent and safe to call more than once.
 */
export function installTextDecoderPolyfill(): void {
  if (PlatformTextDecoder === undefined) return;
  if (platformSupportsUtf16le()) return;

  Object.defineProperty(globalThis, 'TextDecoder', {
    value: Utf16CapableTextDecoder,
    configurable: true,
    writable: true,
  });
}
